spring:
  application:
    name: alert
  datasource:
    url: jdbc:postgresql://160.191.49.50:5432/alert_dev
    username: wqSysadmin
    password: asd123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
server:
  port: 3001