spring:
  application:
    name: alert
  datasource:
    url: jdbc:postgresql://160.191.49.50:5432/alert_dev
    username: wqSysadmin
    password: asd123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: redis
      port: 6379
      password: 1234
  kafka:
    bootstrap-servers: 160.191.49.50:9092
    consumer:
      group-id: clickhuse-consumer
      auto-offset-reset: latest
server:
  port: 3001
  servlet:
    context-path: /api/v0
kafka:
    alert-topic: sensor_data
    message-topic: alert_notification
